name: General Setup
description: checkout & setup python
inputs:
  python-version:  # id of input
    description: the python version to use
    required: false
    default: '3.12'
runs:
  using: composite
  steps:
  - name: Install uv
    uses: astral-sh/setup-uv@v7
    with:
      python-version: ${{inputs.python-version}}
