name: General Setup
description: checkout & setup python
inputs:
  python-version:  # id of input
    description: the python version to use
    required: false
    default: '3.12'
runs:
  using: composite
  steps:
  - name: Install uv
    uses: astral-sh/setup-uv@v5
    with:
      python-version: ${{inputs.python-version}}

  - name: Set up Python
    uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
    with:
      python-version: ${{inputs.python-version}}
      architecture: x64
      allow-prereleases: true
