name: General Setup
description: checkout & setup python
inputs:
  python-version:  # id of input
    description: the python version to use
    required: false
    default: '3.12'
runs:
  using: composite
  steps:
  - name: Install uv
    uses: astral-sh/setup-uv@4db96194c378173c656ce18a155ffc14a9fc4355 # v5.2.2
    with:
      python-version: ${{inputs.python-version}}
