from typing import Literal
from typing import TypeVar

from inline_snapshot._customize._custom_undefined import CustomUndefined

from ._exceptions import UsageError
from ._external._external import External
from ._external._external_file import ExternalFile
from ._external._outsource import Outsourced
from ._external._storage._protocol import StorageLookupError
from ._global_state import state
from ._is import Is
from ._snapshot.generic_value import GenericValue
from ._types import Snapshot


def unwrap(value, which):
    if isinstance(value, GenericValue):
        if which == "new" and not isinstance(value._new_value, CustomUndefined):
            v = value._new_value
        else:
            v = value._old_value
        unwrapped = False

        def unwrap_child(value):
            nonlocal unwrapped
            r, flag = unwrap(value, which)
            unwrapped |= flag
            return r

        return v._map(unwrap_child), unwrapped

    if isinstance(value, Outsourced):
        return (value.data, True)

    if isinstance(value, (External, ExternalFile)):
        try:
            return value._load_value(which), True
        except (UsageError, StorageLookupError):
            return (..., False)

    if isinstance(value, Is):
        return value.value, True

    return value, False


T = TypeVar("T", covariant=True)


def get_snapshot_value(
    snapshot_value: Snapshot[T], which: Literal["new", "old"] = "new"
) -> T:
    """
    Extracts and returns the raw value stored inside a snapshot, removing all inline-snapshot-specific
    wrappers such as those generated by `external()`, `Is()`, or `snapshot()`.

    This function is primarily intended for extension authors who need direct access to the value
    of a previously stored snapshot. For standard test assertions, prefer using the snapshot directly.

    Args:
        snapshot_value: The snapshot object from which to extract the value.

    Returns:
        The unwrapped value contained in the snapshot.

    Example:
        ``` python
        from inline_snapshot import external, snapshot, get_snapshot_value

        s = snapshot([0, external("uuid:e3e70682-c209-4cac-a29f-6fbed82c07cd.json")])

        if record:
            # Store value
            assert s == [0, 5]
        else:
            # Use value from snapshot
            value = get_snapshot_value(s)
            # ... do something with value
        ```

    <!-- TODO: Find a way to test this code in the docs -->
    """
    if state().active:
        return unwrap(snapshot_value, which)[0]
    else:
        return snapshot_value  # type: ignore
