name: deploy development docs
on:
  push:
    branches: [main]

jobs:
  build:
    name: Deploy development docs
    if: "!contains(github.repository, '-insiders/')"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Set up documentation mutex
      uses: suzuki-shunsuke/lock-action@4a69996f86294a4eacc7450392eb70804b6543c4 # v0.2.0
      with:
        mode: lock
        key: docs-lock
        post_unlock: 'true'
        remove_key_when_unlock: 'true'
        max_wait_seconds: '500'
        wait_interval_seconds: '50'

    - run: pip install hatch
    - name: publish docs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "Frank Hoffmann"
        git config user.email "15r10nk@users.noreply.github.com"
        git fetch origin gh-pages --depth=1
        hatch run docs:mike deploy --push development
