name: test docs
on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    name: build docs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
    - uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5.2.0
      with:
        python-version: '3.12'
        architecture: x64
    - run: pip install hatch
    - run: hatch run docs:build
