name: test docs
on:
  pull_request:

jobs:
  build:
    name: Deploy development docs
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - run: pip install hatch
    - name: test docs
      run: |
        hatch run docs:build
