name: test docs
on:
  pull_request:

jobs:
  build:
    name: Deploy development docs
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - run: pip install hatch
    - name: test docs
      run: |
        hatch run docs:build --strict
